-- Populate profiles table with sample data for discover page
-- This script adds sample user data to test the discover page functionality

-- Update existing profiles with sample data
UPDATE public.profiles 
SET 
    role = 'Photographer',
    bio = 'Photographer and Visual Artist. Capturing moments that tell powerful stories.',
    location = 'Delhi, India',
    website = 'https://priyasharma.com',
    skills = ARRAY['Photography', 'Photo Editing', 'Adobe Lightroom', 'Adobe Photoshop'],
    experience_level = 'Senior',
    industry = 'photography',
    portfolio_url = 'https://priyasharma.portfolio.com',
    linkedin_url = 'https://linkedin.com/in/priyasharma',
    github_url = 'https://github.com/priyasharma',
    is_verified = true,
    followers_count = 67,
    projects_count = 12,
    posts_count = 45,
    likes_count = 67
WHERE id = '3c6c0b06-d5fe-43ef-9131-2538cbb80865';

-- Insert additional sample profiles
INSERT INTO public.profiles (
    user_id,
    full_name,
    email,
    role,
    bio,
    location,
    website,
    skills,
    experience_level,
    industry,
    portfolio_url,
    linkedin_url,
    github_url,
    is_verified,
    followers_count,
    projects_count,
    posts_count,
    likes_count
) VALUES 
(
    gen_random_uuid(),
    'Amelia Chen',
    'amelia.chen@example.com',
    'Sound Designer',
    'Sound Designer and Audio Engineer with expertise in film and game audio.',
    'San Francisco, CA',
    'https://ameliachen.com',
    ARRAY['Sound Design', 'Audio Engineering', 'Pro Tools', 'Logic Pro'],
    'Senior',
    'film',
    'https://ameliachen.portfolio.com',
    'https://linkedin.com/in/ameliachen',
    'https://github.com/ameliachen',
    true,
    156,
    8,
    23,
    156
),
(
    gen_random_uuid(),
    'Marcus Thompson',
    'marcus.thompson@example.com',
    'Film Editor',
    'Film Editor and Post-Production Specialist. Crafting compelling narratives through precise editing.',
    'London, UK',
    'https://marcusthompson.com',
    ARRAY['Video Editing', 'Post-Production', 'Adobe Premiere', 'DaVinci Resolve'],
    'Mid',
    'film',
    'https://marcusthompson.portfolio.com',
    'https://linkedin.com/in/marcusthompson',
    'https://github.com/marcusthompson',
    false,
    123,
    15,
    34,
    123
),
(
    gen_random_uuid(),
    'Raj Patel',
    'raj.patel@example.com',
    'Film Director',
    'Film Director and Producer specializing in independent films and documentaries.',
    'Mumbai, India',
    'https://rajpatel.com',
    ARRAY['Directing', 'Producing', 'Screenwriting', 'Cinematography'],
    'Senior',
    'film',
    'https://rajpatel.portfolio.com',
    'https://linkedin.com/in/rajpatel',
    'https://github.com/rajpatel',
    true,
    45,
    6,
    18,
    45
),
(
    gen_random_uuid(),
    'Sarah Johnson',
    'sarah.johnson@example.com',
    'Cinematographer',
    'Cinematographer with 8+ years of experience in film and commercial production. Passionate about visual storytelling.',
    'Los Angeles, CA',
    'https://sarahjohnson.com',
    ARRAY['Cinematography', 'Camera Operation', 'Lighting', 'Color Grading'],
    'Senior',
    'film',
    'https://sarahjohnson.portfolio.com',
    'https://linkedin.com/in/sarahjohnson',
    'https://github.com/sarahjohnson',
    true,
    89,
    20,
    67,
    89
),
(
    gen_random_uuid(),
    'Alex Rodriguez',
    'alex.rodriguez@example.com',
    'VFX Artist',
    'Creative Director and Visual Effects Artist. Bringing stories to life through cutting-edge VFX.',
    'New York, NY',
    'https://alexrodriguez.com',
    ARRAY['VFX', '3D Animation', 'Maya', 'After Effects'],
    'Senior',
    'film',
    'https://alexrodriguez.portfolio.com',
    'https://linkedin.com/in/alexrodriguez',
    'https://github.com/alexrodriguez',
    true,
    234,
    25,
    89,
    234
),
(
    gen_random_uuid(),
    'Emma Wilson',
    'emma.wilson@example.com',
    'Music Composer',
    'Film and TV Music Composer. Creating emotional soundscapes that enhance storytelling.',
    'Nashville, TN',
    'https://emmawilson.com',
    ARRAY['Music Composition', 'Orchestration', 'Logic Pro', 'Cubase'],
    'Mid',
    'music',
    'https://emmawilson.portfolio.com',
    'https://linkedin.com/in/emmawilson',
    'https://github.com/emmawilson',
    false,
    78,
    10,
    29,
    78
),
(
    gen_random_uuid(),
    'David Kim',
    'david.kim@example.com',
    'Animation Director',
    'Animation Director and Character Designer. Bringing characters to life through animation.',
    'Seoul, South Korea',
    'https://davidkim.com',
    ARRAY['Animation', 'Character Design', 'Maya', 'Blender'],
    'Senior',
    'animation',
    'https://davidkim.portfolio.com',
    'https://linkedin.com/in/davidkim',
    'https://github.com/davidkim',
    true,
    145,
    18,
    56,
    145
),
(
    gen_random_uuid(),
    'Lisa Martinez',
    'lisa.martinez@example.com',
    'Documentary Filmmaker',
    'Documentary Filmmaker and Producer. Telling important stories that matter.',
    'Austin, TX',
    'https://lisamartinez.com',
    ARRAY['Documentary', 'Producing', 'Research', 'Interviewing'],
    'Mid',
    'documentary',
    'https://lisamartinez.portfolio.com',
    'https://linkedin.com/in/lisamartinez',
    'https://github.com/lisamartinez',
    false,
    92,
    7,
    31,
    92
);

-- Update the second existing profile
UPDATE public.profiles 
SET 
    role = 'Creative Director',
    bio = 'Creative Director and Brand Strategist. Helping brands tell their stories through visual media.',
    location = 'Toronto, Canada',
    website = 'https://creative-director.com',
    skills = ARRAY['Creative Direction', 'Brand Strategy', 'Visual Design', 'Project Management'],
    experience_level = 'Senior',
    industry = 'advertising',
    portfolio_url = 'https://creative-director.portfolio.com',
    linkedin_url = 'https://linkedin.com/in/creative-director',
    github_url = 'https://github.com/creative-director',
    is_verified = true,
    followers_count = 112,
    projects_count = 35,
    posts_count = 78,
    likes_count = 112
WHERE id = '900c101e-f8e1-47d4-a508-1908114019f5';
