-- Run this SQL in your Supabase SQL Editor to create and populate the companies table

CREATE TABLE IF NOT EXISTS public.companies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    logo TEXT,
    cover_image TEXT,
    category TEXT,
    description TEXT,
    established_year INTEGER,
    founder TEXT,
    services TEXT[],
    languages TEXT[],
    email TEXT,
    phone TEXT,
    website TEXT,
    socials JSONB,
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT DEFAULT 'India',
    maps_location TEXT,
    working_hours TEXT,
    verified BOOLEAN DEFAULT false,
    hiring_now BOOLEAN DEFAULT false,
    open_auditions BOOLEAN DEFAULT false,
    internships_available BOOLEAN DEFAULT false,
    accepting_freshers BOOLEAN DEFAULT false,
    open_for_collaboration BOOLEAN DEFAULT false,
    employee_count INTEGER DEFAULT 0,
    projects_completed INTEGER DEFAULT 0,
    followers_count INTEGER DEFAULT 0,
    rating NUMERIC(3, 2) DEFAULT 0.0,
    reviews_count INTEGER DEFAULT 0,
    featured BOOLEAN DEFAULT false,
    trending BOOLEAN DEFAULT false,
    recently_added BOOLEAN DEFAULT true,
    gallery TEXT[],
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    gst_number TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;

-- Policies for companies table
CREATE POLICY "Enable read access for all users" ON public.companies FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.companies FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for users based on user_id" ON public.companies FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for users based on user_id" ON public.companies FOR DELETE USING (auth.uid() = user_id);

-- Insert dummy data
INSERT INTO public.companies (
    name, logo, cover_image, category, description, established_year, founder, 
    services, languages, email, phone, website, socials, address, city, state, 
    country, maps_location, working_hours, verified, hiring_now, open_auditions, 
    internships_available, accepting_freshers, open_for_collaboration, employee_count, 
    projects_completed, followers_count, rating, reviews_count, featured, trending, 
    gallery
) VALUES 
(
    'Starlight Studios', 
    'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?q=80&w=200&auto=format&fit=crop', 
    'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=1200&auto=format&fit=crop', 
    'Production House', 
    'Award-winning production house specializing in feature films and high-end commercials. With over 15 years of industry experience, Starlight Studios brings stories to life.', 
    2008, 
    'Sarah Jenkins', 
    ARRAY['Feature Films', 'Commercials', 'Post-Production'], 
    ARRAY['English', 'Hindi', 'Tamil'], 
    'contact@starlightstudios.com', 
    '+91 98765 43210', 
    'https://starlightstudios.com', 
    '{"instagram": "https://instagram.com/starlight", "linkedin": "https://linkedin.com/company/starlight"}', 
    '123 Cinema Road, Andheri West', 
    'Mumbai', 
    'Maharashtra', 
    'India', 
    'https://maps.google.com/?q=Starlight+Studios+Mumbai', 
    'Mon-Sat: 10:00 AM - 8:00 PM', 
    true, 
    true, 
    true, 
    false, 
    true, 
    true, 
    150, 
    45, 
    12500, 
    4.8, 
    320, 
    true, 
    true, 
    ARRAY['https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=800', 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800']
),
(
    'Neon VFX', 
    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=200&auto=format&fit=crop', 
    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop', 
    'VFX & Animation', 
    'Leading VFX studio delivering cutting-edge visual effects for blockbusters and web series. Our team of 200+ artists pushes the boundaries of digital creation.', 
    2015, 
    'David Chen', 
    ARRAY['CGI', 'Compositing', 'Motion Graphics', '3D Animation'], 
    ARRAY['English', 'Hindi', 'Telugu'], 
    'hello@neonvfx.com', 
    '+91 91234 56789', 
    'https://neonvfx.com', 
    '{"twitter": "https://twitter.com/neonvfx", "linkedin": "https://linkedin.com/company/neonvfx"}', 
    '45 Tech Park, HITEC City', 
    'Hyderabad', 
    'Telangana', 
    'India', 
    'https://maps.google.com/?q=HITEC+City+Hyderabad', 
    'Mon-Fri: 9:00 AM - 7:00 PM', 
    true, 
    true, 
    false, 
    true, 
    false, 
    false, 
    220, 
    180, 
    8500, 
    4.6, 
    145, 
    true, 
    false, 
    ARRAY['https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800']
),
(
    'Echo Sound Design', 
    'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=200&auto=format&fit=crop', 
    'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=1200&auto=format&fit=crop', 
    'Audio & Sound', 
    'State-of-the-art recording and sound design studio equipped with Dolby Atmos. We specialize in foley, ADR, and cinematic sound mixing.', 
    2010, 
    'Anjali Sharma', 
    ARRAY['Sound Mixing', 'Foley', 'ADR', 'Music Production'], 
    ARRAY['English', 'Hindi', 'Marathi'], 
    'info@echosound.in', 
    '+91 99887 76655', 
    'https://echosound.in', 
    '{"instagram": "https://instagram.com/echosound"}', 
    '88 Melody Lane, Bandra', 
    'Mumbai', 
    'Maharashtra', 
    'India', 
    'https://maps.google.com/?q=Bandra+Mumbai', 
    '24/7 (Booking Required)', 
    true, 
    false, 
    false, 
    true, 
    true, 
    true, 
    25, 
    300, 
    4200, 
    4.9, 
    89, 
    false, 
    true, 
    ARRAY['https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800']
);
