-- Mock data for Casting Calls
-- NOTE: Please ensure you replace the 'creator_id' with a valid user UUID from your public.profiles table before running!

INSERT INTO public.casting_calls (
    id,
    creator_id,
    title,
    project_name,
    production_house,
    casting_director,
    contact_person,
    email,
    phone,
    poster,
    category,
    role_name,
    role_description,
    gender,
    age_min,
    age_max,
    height,
    languages,
    experience,
    compensation,
    location,
    shoot_dates,
    audition_dates,
    audition_venue,
    vacancies,
    max_applications,
    project_description,
    requirements,
    what_to_bring,
    status,
    verified
) VALUES 
(
    gen_random_uuid(),
    (SELECT id FROM public.profiles LIMIT 1), -- Automatically picks the first user as creator
    'Lead Actor for Indie Feature',
    'Midnight Shadows',
    'Lunar Productions',
    'Jane Smith',
    'Jane Smith',
    'casting@lunarproductions.com',
    '+91-9876543210',
    'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?auto=format&fit=crop&q=80&w=800',
    'Feature Film',
    'Detective Miller',
    'A gritty, world-weary detective trying to solve a complex case in the heart of Mumbai. Needs to show a wide range of emotions and perform basic action sequences.',
    'Male',
    35,
    50,
    '5''10" - 6''2"',
    ARRAY['English', 'Hindi'],
    'Experienced',
    'Paid',
    'Mumbai, Maharashtra',
    'Oct 15 - Nov 20, 2026',
    'Sep 1 - Sep 10, 2026',
    'Lunar Studios, Andheri West, Mumbai',
    1,
    200,
    'Midnight Shadows is a neo-noir thriller set in the bustling streets of Mumbai. It explores the dark underbelly of the city through the eyes of a seasoned detective.',
    ARRAY['Must have previous lead role experience', 'Willing to undergo 2 weeks of combat training', 'Available for all shoot dates without conflicts'],
    ARRAY['Headshot', 'Showreel link', 'Identification'],
    'Open',
    true
),
(
    gen_random_uuid(),
    (SELECT id FROM public.profiles LIMIT 1),
    'Supporting Actress for Web Series',
    'College Diaries Season 2',
    'StreamNet Originals',
    'Rahul Verma',
    'Rahul Verma',
    'auditions@streamnet.com',
    '',
    'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&q=80&w=800',
    'Web Series',
    'Priya',
    'A bubbly, energetic college student who is the protagonist''s best friend. Excellent comedic timing required.',
    'Female',
    18,
    25,
    'Any',
    ARRAY['Hindi', 'English'],
    'Any',
    'Paid',
    'Pune, Maharashtra',
    'Nov 2026',
    'Sep 15 - Sep 20, 2026',
    'Virtual Audition (Zoom)',
    1,
    500,
    'The highly anticipated second season of College Diaries following the lives of 4 friends navigating through university life.',
    ARRAY['Good comedic timing', 'Comfortable with improvisation'],
    ARRAY['Monologue video (comedic)'],
    'Open',
    true
),
(
    gen_random_uuid(),
    (SELECT id FROM public.profiles LIMIT 1),
    'Background Talent (Crowd)',
    'The Great Indian Wedding',
    'Karan Films',
    'Pooja Desai',
    'Pooja Desai',
    'pooja.casting@karanfilms.com',
    '+91-9988776655',
    'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&q=80&w=800',
    'Feature Film',
    'Wedding Guests',
    'Looking for energetic individuals of all ages to play wedding guests in a grand musical number.',
    'Any',
    16,
    70,
    'Any',
    ARRAY['Hindi'],
    'Fresher',
    'Paid',
    'Delhi, NCR',
    'Dec 5 - Dec 8, 2026',
    'Oct 1, 2026',
    'Karan Films Office, Delhi',
    50,
    1000,
    'A big budget romantic comedy featuring elaborate wedding sequences.',
    ARRAY['Must bring traditional Indian wedding attire (Lehenga/Sherwani)'],
    ARRAY['Traditional Outfit'],
    'Open',
    false
);
